spring :
  profiles:
    active : dev

logging:
  level:
    org.hibernate.SQL : #debug #sql이 3번씩 출력되길래 주석처리 했습니다. 그래도 2번씩 나옵니다.
    org.hibernate.type : #trace
---
spring :
  config:
    activate:
      on-profile: dev

  datasource:
    url : jdbc:h2:tcp://localhost/~/danshow #h2 url
    username : sa #username
    password:
    driver-class-name: org.h2.Driver

  jpa :
    hibernate:
      ddl-auto: create
    properties:
      hibernate :
        format_sql : true

  data :
    web :
      pageable:
        default-page-size: 10
        max-page-size: 2000







